### ISSUE TITLE
Demo Link NOt Working

### ISSUE THREAD

**Issue by stripathi669** [jhoffman/lsda#1]
Hi,

The demo link mentioned is: http://demo.lsda.berkeleyvision.org:5001 . This is not working for me.

However, http://demo.lsda.berkeleyvision.org/ works for me. Maybe the port address is wrong.

This is not an issue, but I wanted to bring it to your notice.

**Comment by jhoffman** [comment]
Hi,

The correct demo link is: http://demo.lsda.berkeleyvision.org:5001/ I've restarted it for now. 

Thanks!
Judy
